# Generated by Django 3.1 on 2020-08-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prodct_name',
            new_name='product_name',
        ),
    ]
